name: train
run-name: train
on: [pull_request]
jobs:
  running-train:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python run.py
